-- Fix corrupted Korean column names in accident_column_config
UPDATE accident_column_config SET column_name = '재해날짜' WHERE column_key = 'accident_date';
UPDATE accident_column_config SET column_name = '부상형태' WHERE column_key = 'injury_type';  
UPDATE accident_column_config SET column_name = '부상부위' WHERE column_key = 'injury_form';
UPDATE accident_column_config SET column_name = '부상자수' WHERE column_key = 'injured_count';
UPDATE accident_column_config SET column_name = '재해자명단' WHERE column_key = 'injured_person';  -- 재해자명단이 맞음
UPDATE accident_column_config SET column_name = '사고명' WHERE column_key = 'accident_name';
UPDATE accident_column_config SET column_name = '사고번호' WHERE column_key = 'accident_number';
UPDATE accident_column_config SET column_name = '사업장' WHERE column_key = 'workplace';
UPDATE accident_column_config SET column_name = '사고등급' WHERE column_key = 'accident_grade';
UPDATE accident_column_config SET column_name = '귀책사' WHERE column_key = 'responsible_company1';
UPDATE accident_column_config SET column_name = '건물' WHERE column_key = 'building';
UPDATE accident_column_config SET column_name = '층' WHERE column_key = 'floor';
UPDATE accident_column_config SET column_name = '요일' WHERE column_key = 'day_of_week';
UPDATE accident_column_config SET column_name = '등록일' WHERE column_key = 'created_at';
UPDATE accident_column_config SET column_name = '발생구분' WHERE column_key = 'location_category';
UPDATE accident_column_config SET column_name = '발생위치' WHERE column_key = 'location_detail';
UPDATE accident_column_config SET column_name = '사업자번호' WHERE column_key = 'business_number';
UPDATE accident_column_config SET column_name = '사고시간' WHERE column_key = 'accident_time';
UPDATE accident_column_config SET column_name = '책임귀책사(1차) 사업자번호' WHERE column_key = 'responsible_company1_no';
UPDATE accident_column_config SET column_name = '책임귀책사(2차)' WHERE column_key = 'responsible_company2';
UPDATE accident_column_config SET column_name = '책임귀책사(2차) 사업자번호' WHERE column_key = 'responsible_company2_no';
UPDATE accident_column_config SET column_name = '대분류' WHERE column_key = 'major_category';
UPDATE accident_column_config SET column_name = '사고경위' WHERE column_key = 'accident_description';
UPDATE accident_column_config SET column_name = '원인분석' WHERE column_key = 'cause_analysis';
UPDATE accident_column_config SET column_name = '재발방지대책' WHERE column_key = 'preventive_measures';
UPDATE accident_column_config SET column_name = '부상정도' WHERE column_key = 'injury_level';
UPDATE accident_column_config SET column_name = '신고자명' WHERE column_key = 'reporter_name';
UPDATE accident_column_config SET column_name = '사고내용' WHERE column_key = 'accident_content';
UPDATE accident_column_config SET column_name = '귀책사(1차형태)' WHERE column_key = 'company_1cha';
UPDATE accident_column_config SET column_name = '귀책사(1차형태) 사업자번호' WHERE column_key = 'company_1cha_bizno';
UPDATE accident_column_config SET column_name = '귀책부서' WHERE column_key = 'incharge';
UPDATE accident_column_config SET column_name = '귀책부서 부서코드' WHERE column_key = 'incharge_code';
UPDATE accident_column_config SET column_name = '귀책담당자(팀장급)' WHERE column_key = 'incharge_person';
UPDATE accident_column_config SET column_name = '귀책담당자 ID' WHERE column_key = 'incharge_person_id';
UPDATE accident_column_config SET column_name = '귀책담당자 부서' WHERE column_key = 'incharge_person_dept';
UPDATE accident_column_config SET column_name = '업체명' WHERE column_key = 'company_name';
UPDATE accident_column_config SET column_name = '업체명 사업자번호' WHERE column_key = 'company_name_bizno';